# Generated by Django 4.2.30 on 2026-08-21 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0001_initial'),
        ('food_profiles', '0002_populate_restrictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('preparation_time', models.PositiveIntegerField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='establishments.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_restrictions', to='recipes.recipe')),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_restrictions', to='food_profiles.restriction')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='restrictions',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='recipes.RecipeRestriction', to='food_profiles.restriction'),
        ),
        migrations.AddConstraint(
            model_name='reciperestriction',
            constraint=models.UniqueConstraint(fields=('recipe', 'restriction'), name='unique_recipe_restriction'),
        ),
    ]
