# Generated by Django 4.2.30 on 2026-08-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='reciperestriction',
            name='relation_type',
            field=models.CharField(choices=[('blocks', 'Bloquea'), ('adapted_for', 'Adaptada para')], default='blocks', max_length=20),
        ),
    ]
