# Generated by Django 4.2.30 on 2026-08-18 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('restriction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='food_profiles.restriction')),
                ('allergy_type', models.CharField(choices=[('GLUTEN', 'Gluten'), ('CRUSTACEANS', 'Crustáceos'), ('EGGS', 'Huevos'), ('FISH', 'Pescado'), ('PEANUTS', 'Cacahuetes'), ('SOY', 'Soja'), ('DAIRY', 'Lácteos'), ('NUTS', 'Frutos de cáscara'), ('CELERY', 'Apio'), ('MUSTARD', 'Mostaza'), ('SESAME', 'Semillas de sésamo'), ('SULPHITES', 'Dióxido de azufre y sulfitos'), ('LUPIN', 'Altramuces'), ('MOLLUSCS', 'Moluscos')], max_length=30, unique=True)),
            ],
            bases=('food_profiles.restriction',),
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('restriction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='food_profiles.restriction')),
                ('diet_type', models.CharField(choices=[('VEGETARIAN', 'Vegetariano'), ('VEGAN', 'Vegano'), ('PESCETARIAN', 'Pescetariano'), ('HALAL', 'Halal'), ('KOSHER', 'Kosher')], max_length=30, unique=True)),
            ],
            bases=('food_profiles.restriction',),
        ),
        migrations.CreateModel(
            name='FoodProfileRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_restrictions', to='food_profiles.foodprofile')),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_restrictions', to='food_profiles.restriction')),
            ],
        ),
        migrations.AddField(
            model_name='foodprofile',
            name='restrictions',
            field=models.ManyToManyField(blank=True, related_name='food_profiles', through='food_profiles.FoodProfileRestriction', to='food_profiles.restriction'),
        ),
        migrations.AddConstraint(
            model_name='foodprofilerestriction',
            constraint=models.UniqueConstraint(fields=('food_profile', 'restriction'), name='unique_food_profile_restriction'),
        ),
    ]
