# Generated by Django 4.2.30 on 2026-08-20 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_profiles', '0002_populate_restrictions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('cross_contamination', models.TextField(blank=True)),
                ('restrictions_info', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='establishments.establishment')),
            ],
        ),
        migrations.AddField(
            model_name='establishment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='establishments', to='establishments.tag'),
        ),
        migrations.CreateModel(
            name='DishRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence_type', models.CharField(choices=[('contains', 'Contiene'), ('may_contain', 'Puede contener'), ('traces', 'Trazas')], max_length=20)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_restrictions', to='establishments.dish')),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_restrictions', to='food_profiles.restriction')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='establishments.establishment'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restrictions',
            field=models.ManyToManyField(blank=True, related_name='dishes', through='establishments.DishRestriction', to='food_profiles.restriction'),
        ),
        migrations.AddConstraint(
            model_name='dishrestriction',
            constraint=models.UniqueConstraint(fields=('dish', 'restriction'), name='unique_dish_restriction'),
        ),
    ]
