# Generated by Django 4.2.30 on 2026-08-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
